#!/usr/bin/env python3
"""Validate canonical documentation layout and deterministic Markdown quality.

This validator checks machine-verifiable presentation quality only. It does not
claim semantic correctness or actual human comprehension.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from project_profile import (
    PROFILE_FILE,
    contract_settings,
    documentation_settings,
    parse_profile,
    required_docs,
)

GENERATED_MARKER = "GENERATED BY PROJECT TRUTH COMPILER - DO NOT EDIT"

CANONICAL_DOCS = {
    "SYSTEM_OVERVIEW.md",
    "PROJECT_MANIFEST.md",
    "CURRENT_STATE.md",
    "SOURCE_AUTHORITY_MAP.md",
    "ARCHITECTURE.md",
    "WORKFLOW_STATE_MACHINE.md",
    "SEQUENCE_CONTRACTS.md",
    "MODULE_MAP.md",
    "SYMBOL_INDEX.md",
    "FLOW_INDEX.md",
    "TEST_ACCEPTANCE_MATRIX.md",
    "DOC_SYNC_MATRIX.md",
    "PROJECT_TRUTH_SYNC.md",
    "API_CONTRACTS.md",
    "DATA_CONTRACTS.md",
    "UI_INFORMATION_ARCHITECTURE.md",
    "RUNBOOK.md",
    "DECISIONS.md",
    "KNOWN_DEFECTS.md",
    "GLOSSARY.md",
    "CHANGELOG.md",
}

SYSTEM_OVERVIEW_HEADINGS = {
    "## One-minute summary",
    "## System at a glance",
    "## Major components",
    "## Main data flow",
    "## Main user workflows",
    "## Lifecycle and state",
    "## Authority model",
    "## Mutable vs immutable",
    "## Failure and recovery",
    "## Current project state",
    "## Proven vs not proven",
    "## Human comprehension gate",
}


def normalized_shape(text: str) -> tuple[bool, list[str]]:
    failures: list[str] = []
    if not text.endswith("\n"):
        failures.append("MISSING_FINAL_NEWLINE")

    lines = text.splitlines()
    in_fence = False
    blank_run = 0
    h1_count = 0
    previous_heading = 0

    for index, line in enumerate(lines, start=1):
        if line.rstrip() != line:
            failures.append(f"TRAILING_WHITESPACE:{index}")

        stripped = line.lstrip()
        if stripped.startswith("~~~") or stripped.startswith(chr(96) * 3):
            in_fence = not in_fence
            blank_run = 0
            continue

        if in_fence:
            continue

        if not line:
            blank_run += 1
            if blank_run > 1:
                failures.append(f"EXCESSIVE_BLANK_LINES:{index}")
            continue
        blank_run = 0

        heading = re.match(r"^(#{1,6})\s+\S", line)
        if heading:
            level = len(heading.group(1))
            if level == 1:
                h1_count += 1
            if previous_heading and level > previous_heading + 1:
                failures.append(
                    f"HEADING_LEVEL_JUMP:{index}:{previous_heading}->{level}"
                )
            previous_heading = level

        if len(line) > 3000:
            failures.append(f"EXTREME_LINE_LENGTH:{index}:{len(line)}")

    if h1_count != 1:
        failures.append(f"H1_COUNT:{h1_count}")

    if re.search(r"\breplace-me\b", text, re.IGNORECASE):
        failures.append("PLACEHOLDER_REPLACE_ME")

    return not failures, failures


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--report", default="")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    profile_path = root / PROFILE_FILE
    if not profile_path.is_file():
        print("FAIL MISSING_PROJECT_PROFILE")
        return 1

    try:
        profile = parse_profile(profile_path)
        documentation = documentation_settings(profile)
        required = required_docs(profile)
        contracts = contract_settings(profile)
    except Exception as exc:
        print("FAIL PROJECT_PROFILE_INVALID:" + str(exc))
        return 1

    docs_root = root / str(documentation.get("docs_root", "docs"))
    failures: list[str] = []
    warnings: list[str] = []
    checked = 0
    metrics: dict[str, dict[str, int]] = {}

    if docs_root != root / "docs":
        failures.append("DOC_LAYOUT_INVALID_ROOT:" + str(docs_root))

    if not docs_root.is_dir():
        failures.append("DOCS_ROOT_MISSING:docs")

    for name in sorted(CANONICAL_DOCS):
        if (root / name).is_file():
            failures.append("DUPLICATE_CANONICAL_DOC_AT_REPO_ROOT:" + name)

    expected_names = {name for name in required if name != PROFILE_FILE}
    for key, value in contracts.items():
        if value != "not_applicable":
            mapping = {
                "api_contracts": "API_CONTRACTS.md",
                "data_contracts": "DATA_CONTRACTS.md",
                "ui_information_architecture": "UI_INFORMATION_ARCHITECTURE.md",
                "runbook": "RUNBOOK.md",
                "decisions": "DECISIONS.md",
                "known_defects": "KNOWN_DEFECTS.md",
                "glossary": "GLOSSARY.md",
                "changelog": "CHANGELOG.md",
            }
            expected_names.add(mapping[key])

    # Compiler always emits these orientation/history projections.
    expected_names.update(
        {
            "SYSTEM_OVERVIEW.md",
            "PROJECT_MANIFEST.md",
            "CURRENT_STATE.md",
            "MODULE_MAP.md",
            "TEST_ACCEPTANCE_MATRIX.md",
            "DECISIONS.md",
            "KNOWN_DEFECTS.md",
            "GLOSSARY.md",
        }
    )

    for name in sorted(expected_names):
        path = docs_root / name
        if not path.is_file():
            failures.append("MISSING_CANONICAL_DOC:docs/" + name)
            continue

        checked += 1
        raw = path.read_bytes()
        if b"\r" in raw:
            failures.append("DOC_QUALITY:" + name + ":NON_LF_NEWLINE")
        text = raw.decode("utf-8", errors="strict")
        if GENERATED_MARKER not in text:
            failures.append("GENERATED_MARKER_MISSING:docs/" + name)

        ok, shape_failures = normalized_shape(text)
        if not ok:
            failures.extend(
                "DOC_QUALITY:" + name + ":" + item for item in shape_failures
            )

        metrics[name] = {
            "lines": len(text.splitlines()),
            "characters": len(text),
        }

    overview = docs_root / "SYSTEM_OVERVIEW.md"
    if overview.is_file():
        text = overview.read_text(encoding="utf-8", errors="strict")
        for heading in sorted(SYSTEM_OVERVIEW_HEADINGS):
            if heading not in text:
                failures.append("SYSTEM_OVERVIEW_SECTION_MISSING:" + heading)

    if (root / "README.md").is_file():
        readme = (root / "README.md").read_text(
            encoding="utf-8", errors="ignore"
        )
        for ref in (
            "docs/SYSTEM_OVERVIEW.md",
            "docs/CURRENT_STATE.md",
            "docs/PROJECT_MANIFEST.md",
        ):
            if ref not in readme:
                warnings.append("README_CANONICAL_DOC_LINK_MISSING:" + ref)

    report = {
        "schema_version": 1,
        "docs_root": "docs",
        "docs_checked": checked,
        "doc_layout": "FAIL" if any(
            item.startswith(("DOC_LAYOUT_", "DUPLICATE_CANONICAL_DOC_AT_REPO_ROOT"))
            for item in failures
        ) else "PASS",
        "project_docs_normalized": "FAIL" if any(
            item.startswith("DOC_QUALITY:") for item in failures
        ) else "PASS",
        "doc_readability": "FAIL" if failures else "PASS",
        "metrics": metrics,
        "failures": failures,
        "warnings": warnings,
        "machine_scope": (
            "Layout, deterministic formatting, required structure, and obvious "
            "presentation defects only; semantic readability still requires "
            "the Human Comprehension Gate."
        ),
        "result": "FAIL" if failures else "PASS",
    }

    payload = json.dumps(report, indent=2, sort_keys=True)
    print(payload)

    if args.report:
        report_path = Path(args.report)
        if not report_path.is_absolute():
            report_path = root / report_path
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(payload + "\n", encoding="utf-8")

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
